/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as interfaceERc20Sol from "./InterfaceERc20.sol";
export type { interfaceERc20Sol };
import type * as interfaceERc721Sol from "./InterfaceERc721.sol";
export type { interfaceERc721Sol };
import type * as interfaceErc1155Sol from "./InterfaceErc1155.sol";
export type { interfaceErc1155Sol };
export type { Lock } from "./Lock";
export type { RewardERC1155 } from "./RewardERC1155";
export type { RewardERC20 } from "./RewardERC20";
export type { RewardERC721 } from "./RewardERC721";
export type { Staking } from "./Staking";
