/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IrewardERC1155,
  IrewardERC1155Interface,
} from "../../../contracts/InterfaceErc1155.sol/IrewardERC1155";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
    ],
    name: "_mint",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
    ],
    name: "mintBy",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IrewardERC1155__factory {
  static readonly abi = _abi;
  static createInterface(): IrewardERC1155Interface {
    return new utils.Interface(_abi) as IrewardERC1155Interface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IrewardERC1155 {
    return new Contract(address, _abi, signerOrProvider) as IrewardERC1155;
  }
}
