/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as interfaceERc20Sol from "./InterfaceERc20.sol";
export * as interfaceERc721Sol from "./InterfaceERc721.sol";
export * as interfaceErc1155Sol from "./InterfaceErc1155.sol";
export { Lock__factory } from "./Lock__factory";
export { RewardERC1155__factory } from "./RewardERC1155__factory";
export { RewardERC20__factory } from "./RewardERC20__factory";
export { RewardERC721__factory } from "./RewardERC721__factory";
export { Staking__factory } from "./Staking__factory";
