/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IrewardERC721,
  IrewardERC721Interface,
} from "../../../contracts/InterfaceERc721.sol/IrewardERC721";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
    ],
    name: "safeMint",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "from",
        type: "address",
      },
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
    ],
    name: "transferFrom",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IrewardERC721__factory {
  static readonly abi = _abi;
  static createInterface(): IrewardERC721Interface {
    return new utils.Interface(_abi) as IrewardERC721Interface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IrewardERC721 {
    return new Contract(address, _abi, signerOrProvider) as IrewardERC721;
  }
}
